### ISSUE TITLE
Only check the HEAD commit of a PR

### ISSUE THREAD

**Issue by sonrohan** [wagoid/commitlint-github-action#363] opened 2022-03-31 19:34 UTC
Could we add a flag that only checks the head commit of the feature branch on PR?

If I have a branch like this

```
TICKET-123 Do some work
fix x
fix y
add unit test
```

I want this to only run on `TICKET-123 Do some work`

**Comment by jdbruijn** [comment] 2022-04-01 06:36
I'm not quite sure, but I think you could already achieve that by setting `fetch-depth: 1` in the checkout action, don't configure it [as `1` is the default](https://github.com/actions/checkout/tree/v3.0.0#usage). The way this action works is by getting the git commit information from the local environment, so if you only fetch a single commit we'd run on just that (I think). Please let me know if that resolves your issue!

**Comment by sonrohan** [comment] 2022-04-01 06:38
Thanks for the quick response! Actually tried to change the fetch depth to 1 and also even tried 2, and it threw some errors. I'm on my phone right now so I don't have them, but I can update this comment later with the relevant error. It didn't seem to worth though is the tldr

**Comment by jdbruijn** [comment] 2022-04-01 06:42
Ah yeah, I guess you're right. In the PR we'll get a commit SHA range from GitHub, so we'll try to run on that range. In the case `fetch-depth: 1` however, not all commits we'd need are available and you get an error (see #340). Then this is a valid feature request and I'll leave it up to @wagoid to decide what to do with it 😉

**Comment by sonrohan** [comment] 2022-04-01 06:43
Thanks! If you need someone to contribute this to the codebase I'm happy to take a crack at it. Just let me know.

**Comment by wagoid** [comment] 2022-04-06 21:17
Hey @sonrohan! That seems like a nice feature. @jdbruijn your comment made me wonder if we should support a similar `fetch-depth` param in the action? So if we pass `fetch-depth: 1` to our action it would analyze only the HEAD commit in the end.

> Thanks! If you need someone to contribute this to the codebase I'm happy to take a crack at it. Just let me know.

@sonrohan thanks!  I would be happy to review it 💪

**Comment by jdbruijn** [comment] 2022-04-07 09:16
Yeah I think we should name it `commit-depth` or something like that to avoid confusion with the checkout parameter.

**Comment by Sakethtadimeti** [comment] 2022-11-15 11:18
Folks, is this closed?
I have a similar use case to only test against the latest commit.

**Comment by wagoid** [comment] 2022-11-17 13:28
Hi @Sakethtadimeti, the issue is still open. I won't be able to work on it in the near future, but happy to review any PRs!

**Comment by Sakethtadimeti** [comment] 2022-11-19 18:18
@wagoid Please provide `write` access.

**Comment by wagoid** [comment] 2022-11-19 19:00
@Sakethtadimeti you will need to create a fork of the repo, then submit a pull request.

**Comment by Sakethtadimeti** [comment] 2022-11-20 08:20
Hey @wagoid, please have a look at this PR https://github.com/wagoid/commitlint-github-action/pull/595.
Many thanks for considering my request.

**Comment by SvenStaehs** [comment] 2023-07-19 09:19
the PR is merged, can the issue be closed?

**Comment by Sakethtadimeti** [comment] 2023-07-24 01:58
> the PR is merged, can the issue be closed?

Sure 😃

**Closed** 2023-07-24 08:24 UTC
