### ISSUE TITLE
PR check only "title" commit

### ISSUE THREAD

**Issue by asafdl** [wagoid/commitlint-github-action#325] opened 2022-01-25 13:57 UTC
Hi, is there a way to check only the "top commit" or "title" for a merge commit? it seems unnecessary to make every single commit a in a PR a conventional commit

**Comment by jdbruijn** [comment] 2022-01-25 14:56
Duplicate of #190.

This action probably won't do that, based on the previous answer on this request: https://github.com/wagoid/commitlint-github-action/issues/190#issuecomment-880505974.

**Closed by jdbruijn** 2022-01-25 14:56 UTC

**Comment by jdbruijn** [comment] 2022-01-25 14:58
Duplicate of #190
